function plot_title(clus_ax, cluster_index, all_spikes, class_spikes, par)
    % Get the number of spikes in the cluster
    aux_num = length(class_spikes);
    SNR = cluster_SNR(all_spikes, class_spikes);
    total_time = par.file_metadata(4);
    title( ...
        clus_ax, ...
        sprintf('Cluster %d:  # %d (%.1f%%)\n%.2fHz  SNR=%.1f', ...
            cluster_index, ...
            aux_num, ...
            aux_num ./ size(all_spikes, 1) .* 100, ...
            aux_num ./ total_time, ...
            SNR), ...
        'Fontweight','bold');

